-- ============================================================
-- ICJ Enterprise Platform
-- Migration: Create token management tables
-- Date: 2026-07-30
-- ============================================================

create table if not exists public.token_masters (
  id bigint generated by default as identity primary key,
  token_code text unique,
  token_name text not null,
  token_symbol text not null,
  unit_value numeric default 1,
  max_supply numeric default 0,
  circulating_supply numeric default 0,
  status text default 'Active',
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

create table if not exists public.token_transactions (
  id bigint generated by default as identity primary key,
  transaction_no text unique,
  token_no text,
  transaction_type text not null,
  member_id text,
  to_member_id text,
  wallet_id bigint,
  amount numeric default 0,
  unit_value numeric default 1,
  reference_no text,
  narration text,
  status text default 'Posted',
  created_by text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

create table if not exists public.token_allocations (
  id bigint generated by default as identity primary key,
  allocation_no text unique,
  member_id text,
  token_no text,
  batch_no text,
  amount numeric default 0,
  status text default 'Allocated',
  created_at timestamp with time zone default timezone('utc'::text, now())
);

create table if not exists public.token_wallet_links (
  id bigint generated by default as identity primary key,
  member_id text,
  wallet_id bigint,
  token_enabled boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

create table if not exists public.token_reports (
  id bigint generated by default as identity primary key,
  report_no text unique,
  report_name text,
  report_type text,
  filters jsonb,
  payload jsonb,
  created_by text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

create index if not exists token_masters_code_idx on public.token_masters(token_code);
create index if not exists token_transactions_member_idx on public.token_transactions(member_id);
create index if not exists token_transactions_type_idx on public.token_transactions(transaction_type);
create index if not exists token_transactions_created_idx on public.token_transactions(created_at);
create index if not exists token_allocations_member_idx on public.token_allocations(member_id);
create index if not exists token_wallet_links_member_idx on public.token_wallet_links(member_id);
create index if not exists token_reports_type_idx on public.token_reports(report_type);
