-- ============================================================
-- ICJ Enterprise Platform
-- Migration: Create legal management extension tables
-- Date: 2026-07-30
-- ============================================================

create table if not exists public.legal_clients (
  id bigint generated by default as identity primary key,
  client_no text unique,
  member_id text,
  name text not null,
  mobile text,
  email text,
  client_type text default 'External',
  status text default 'Active',
  created_at timestamp with time zone default timezone('utc'::text, now())
);

create table if not exists public.legal_courts (
  id bigint generated by default as identity primary key,
  court_code text unique,
  name text not null,
  court_type text,
  location text,
  status text default 'Active',
  created_at timestamp with time zone default timezone('utc'::text, now())
);

create table if not exists public.legal_advocates (
  id bigint generated by default as identity primary key,
  advocate_no text unique,
  name text not null,
  bar_council_no text,
  mobile text,
  specialization text,
  status text default 'Active',
  created_at timestamp with time zone default timezone('utc'::text, now())
);

create table if not exists public.legal_notices (
  id bigint generated by default as identity primary key,
  notice_no text unique,
  case_id bigint,
  title text not null,
  notice_type text,
  issued_to text,
  issued_date date,
  status text default 'Issued',
  created_at timestamp with time zone default timezone('utc'::text, now())
);

create table if not exists public.legal_hearings (
  id bigint generated by default as identity primary key,
  hearing_no text unique,
  case_id bigint,
  hearing_date date,
  court_name text,
  stage text,
  remarks text,
  status text default 'Scheduled',
  created_at timestamp with time zone default timezone('utc'::text, now())
);

create table if not exists public.legal_timelines (
  id bigint generated by default as identity primary key,
  timeline_no text unique,
  case_id bigint,
  event_type text,
  title text,
  detail text,
  event_date date,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

create table if not exists public.legal_case_links (
  id bigint generated by default as identity primary key,
  case_id bigint,
  link_type text,
  document_id bigint,
  reference text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

create index if not exists legal_clients_member_idx on public.legal_clients(member_id);
create index if not exists legal_courts_name_idx on public.legal_courts(name);
create index if not exists legal_advocates_name_idx on public.legal_advocates(name);
create index if not exists legal_notices_case_idx on public.legal_notices(case_id);
create index if not exists legal_hearings_case_idx on public.legal_hearings(case_id);
create index if not exists legal_hearings_date_idx on public.legal_hearings(hearing_date);
create index if not exists legal_timelines_case_idx on public.legal_timelines(case_id);
create index if not exists legal_case_links_case_idx on public.legal_case_links(case_id);
