-- ============================================================
-- ICJ Enterprise Platform
-- Migration: Role and Permission Foundation
-- Date: 2026-07-30
-- ============================================================

create table if not exists public.role_categories (
  id bigint generated by default as identity primary key,
  category_key text unique not null,
  category_name text not null,
  display_order integer default 0,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

create table if not exists public.roles (
  id bigint generated by default as identity primary key,
  role_code text unique not null,
  role_name text not null,
  role_category_id bigint not null references public.role_categories(id) on delete restrict,
  legacy_role text not null default 'member',
  is_public_registration boolean default true,
  is_system_role boolean default false,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

create table if not exists public.permissions (
  id bigint generated by default as identity primary key,
  permission_key text unique not null,
  module_key text not null,
  permission_name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

create table if not exists public.role_permissions (
  id bigint generated by default as identity primary key,
  role_id bigint not null references public.roles(id) on delete cascade,
  permission_id bigint not null references public.permissions(id) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  unique(role_id, permission_id)
);

create table if not exists public.user_roles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role_id bigint not null references public.roles(id) on delete restrict,
  assigned_by uuid,
  assigned_at timestamp with time zone default timezone('utc'::text, now())
);

alter table public.profiles add column if not exists role_code text;
alter table public.profiles add column if not exists role_category text;
alter table public.profiles add column if not exists legacy_role text;

create index if not exists roles_category_idx on public.roles(role_category_id);
create index if not exists roles_public_idx on public.roles(is_public_registration);
create index if not exists permissions_module_idx on public.permissions(module_key);
create index if not exists role_permissions_role_idx on public.role_permissions(role_id);
create index if not exists user_roles_role_idx on public.user_roles(role_id);
create index if not exists profiles_role_code_idx on public.profiles(role_code);

insert into public.role_categories (category_key, category_name, display_order)
values
  ('administration', 'Administration', 1),
  ('community', 'Community', 2),
  ('service_users', 'Service Users', 3),
  ('partners', 'Partners', 4)
on conflict (category_key) do nothing;

insert into public.roles (role_code, role_name, role_category_id, legacy_role, is_public_registration, is_system_role)
select 'super_admin', 'Super Admin', rc.id, 'admin', false, true
from public.role_categories rc
where rc.category_key = 'administration'
on conflict (role_code) do nothing;

insert into public.roles (role_code, role_name, role_category_id, legacy_role, is_public_registration, is_system_role)
select 'system_admin', 'System Admin', rc.id, 'admin', true, true
from public.role_categories rc
where rc.category_key = 'administration'
on conflict (role_code) do nothing;

insert into public.roles (role_code, role_name, role_category_id, legacy_role, is_public_registration, is_system_role)
select 'organization_admin', 'Organization Admin', rc.id, 'admin', true, false
from public.role_categories rc
where rc.category_key = 'administration'
on conflict (role_code) do nothing;

insert into public.roles (role_code, role_name, role_category_id, legacy_role, is_public_registration, is_system_role)
select 'professional_member', 'Professional Member', rc.id, 'member', true, false
from public.role_categories rc
where rc.category_key = 'community'
on conflict (role_code) do nothing;

insert into public.roles (role_code, role_name, role_category_id, legacy_role, is_public_registration, is_system_role)
select 'member', 'Member', rc.id, 'member', true, false
from public.role_categories rc
where rc.category_key = 'community'
on conflict (role_code) do nothing;

insert into public.roles (role_code, role_name, role_category_id, legacy_role, is_public_registration, is_system_role)
select 'volunteer', 'Volunteer', rc.id, 'member', true, false
from public.role_categories rc
where rc.category_key = 'community'
on conflict (role_code) do nothing;

insert into public.roles (role_code, role_name, role_category_id, legacy_role, is_public_registration, is_system_role)
select 'employee', 'Employee', rc.id, 'employee', true, false
from public.role_categories rc
where rc.category_key = 'community'
on conflict (role_code) do nothing;

insert into public.roles (role_code, role_name, role_category_id, legacy_role, is_public_registration, is_system_role)
select 'help_seeker', 'Help Seeker', rc.id, 'member', true, false
from public.role_categories rc
where rc.category_key = 'service_users'
on conflict (role_code) do nothing;

insert into public.roles (role_code, role_name, role_category_id, legacy_role, is_public_registration, is_system_role)
select 'service_applicant', 'Service Applicant', rc.id, 'member', true, false
from public.role_categories rc
where rc.category_key = 'service_users'
on conflict (role_code) do nothing;

insert into public.roles (role_code, role_name, role_category_id, legacy_role, is_public_registration, is_system_role)
select 'citizen_applicant', 'Citizen Applicant', rc.id, 'member', true, false
from public.role_categories rc
where rc.category_key = 'service_users'
on conflict (role_code) do nothing;

insert into public.roles (role_code, role_name, role_category_id, legacy_role, is_public_registration, is_system_role)
select 'support_partner', 'Support Partner', rc.id, 'member', true, false
from public.role_categories rc
where rc.category_key = 'partners'
on conflict (role_code) do nothing;

insert into public.roles (role_code, role_name, role_category_id, legacy_role, is_public_registration, is_system_role)
select 'guest', 'Guest', rc.id, 'member', true, false
from public.role_categories rc
where rc.category_key = 'partners'
on conflict (role_code) do nothing;

insert into public.permissions (permission_key, module_key, permission_name)
values
  ('membership.view', 'membership', 'View Membership'),
  ('membership.create', 'membership', 'Create Membership Data'),
  ('membership.update', 'membership', 'Update Membership Data'),
  ('membership.delete', 'membership', 'Delete Membership Data'),
  ('wallet.view', 'wallet', 'View Wallet'),
  ('wallet.credit', 'wallet', 'Credit Wallet'),
  ('wallet.debit', 'wallet', 'Debit Wallet'),
  ('wallet.transfer', 'wallet', 'Transfer Wallet Balance'),
  ('payments.view', 'payments', 'View Payments'),
  ('payments.create', 'payments', 'Create Payment Records'),
  ('payments.refund', 'payments', 'Refund Payments'),
  ('payments.export', 'payments', 'Export Payments'),
  ('legal.view', 'legal', 'View Legal Cases'),
  ('legal.create', 'legal', 'Create Legal Cases'),
  ('legal.update', 'legal', 'Update Legal Cases'),
  ('legal.delete', 'legal', 'Delete Legal Cases'),
  ('documents.view', 'documents', 'View Documents'),
  ('documents.upload', 'documents', 'Upload Documents'),
  ('documents.download', 'documents', 'Download Documents'),
  ('documents.delete', 'documents', 'Delete Documents'),
  ('ai.view', 'ai', 'View AI Module'),
  ('ai.run', 'ai', 'Run AI Actions'),
  ('ai.manage', 'ai', 'Manage AI Configuration'),
  ('reports.view', 'reports', 'View Reports'),
  ('reports.export', 'reports', 'Export Reports'),
  ('notifications.view', 'notifications', 'View Notifications'),
  ('notifications.manage', 'notifications', 'Manage Notifications')
on conflict (permission_key) do nothing;

insert into public.user_roles (user_id, role_id)
select p.id, r.id
from public.profiles p
join public.roles r on r.role_code = coalesce(nullif(p.role_code, ''), 'member')
where not exists (
  select 1 from public.user_roles ur where ur.user_id = p.id
);

update public.profiles p
set role_code = coalesce(nullif(p.role_code, ''), 'member'),
    role_category = coalesce(nullif(p.role_category, ''), 'community'),
    legacy_role = coalesce(nullif(p.legacy_role, ''), 'member')
where p.role_code is null or p.role_code = '' or p.role_category is null or p.role_category = '' or p.legacy_role is null or p.legacy_role = '';

alter table if exists public.role_categories enable row level security;
alter table if exists public.roles enable row level security;
alter table if exists public.permissions enable row level security;
alter table if exists public.role_permissions enable row level security;
alter table if exists public.user_roles enable row level security;

drop policy if exists role_categories_select_authenticated on public.role_categories;
create policy role_categories_select_authenticated on public.role_categories
for select using (auth.role() = 'authenticated');

drop policy if exists roles_select_authenticated on public.roles;
create policy roles_select_authenticated on public.roles
for select using (auth.role() = 'authenticated');

drop policy if exists permissions_select_authenticated on public.permissions;
create policy permissions_select_authenticated on public.permissions
for select using (auth.role() = 'authenticated');

drop policy if exists role_permissions_select_authenticated on public.role_permissions;
create policy role_permissions_select_authenticated on public.role_permissions
for select using (auth.role() = 'authenticated');

drop policy if exists user_roles_select_own_or_staff on public.user_roles;
create policy user_roles_select_own_or_staff on public.user_roles
for select using (
  auth.uid() = user_id
  or (auth.jwt() ->> 'role') in ('admin', 'employee')
);

drop policy if exists user_roles_insert_self_non_super on public.user_roles;
create policy user_roles_insert_self_non_super on public.user_roles
for insert with check (
  auth.uid() = user_id
  and role_id <> (select id from public.roles where role_code = 'super_admin')
);

drop policy if exists user_roles_update_staff on public.user_roles;
create policy user_roles_update_staff on public.user_roles
for update using ((auth.jwt() ->> 'role') in ('admin', 'employee'))
with check ((auth.jwt() ->> 'role') in ('admin', 'employee'));
