-- ============================================================
-- ICJ Enterprise Platform
-- Migration: Document Management MVP foundation
-- Date: 2026-07-30
-- ============================================================

create table if not exists public.document_categories (
  id bigint generated by default as identity primary key,
  category_code text unique,
  category_name text not null,
  category_type text default 'General',
  status text default 'Active',
  created_at timestamp with time zone default timezone('utc'::text, now())
);

create table if not exists public.document_tags (
  id bigint generated by default as identity primary key,
  tag_name text unique,
  status text default 'Active',
  created_at timestamp with time zone default timezone('utc'::text, now())
);

create table if not exists public.document_versions (
  id bigint generated by default as identity primary key,
  version_no text,
  document_id bigint,
  file_name text,
  file_type text,
  file_path text,
  file_url text,
  file_size numeric default 0,
  note text,
  uploaded_by text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

create table if not exists public.document_audit_logs (
  id bigint generated by default as identity primary key,
  log_no text unique,
  document_id bigint,
  document_no text,
  action text,
  detail text,
  actor_role text,
  actor_id text,
  event_at timestamp with time zone default timezone('utc'::text, now())
);

create table if not exists public.document_links (
  id bigint generated by default as identity primary key,
  document_id bigint,
  module_type text,
  reference_id text,
  relation_type text,
  metadata jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

create table if not exists public.document_tag_map (
  id bigint generated by default as identity primary key,
  document_id bigint,
  tag_id bigint,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

create index if not exists document_categories_name_idx on public.document_categories(category_name);
create index if not exists document_tags_name_idx on public.document_tags(tag_name);
create index if not exists document_versions_document_idx on public.document_versions(document_id);
create index if not exists document_audit_logs_document_idx on public.document_audit_logs(document_id);
create index if not exists document_audit_logs_event_idx on public.document_audit_logs(event_at);
create index if not exists document_links_document_idx on public.document_links(document_id);
create index if not exists document_links_ref_idx on public.document_links(module_type, reference_id);
create index if not exists document_tag_map_document_idx on public.document_tag_map(document_id);
