const Modules = [
  // CORE
  {
    id: "dashboard",
    name: "Dashboard",
    category: "Core",
    route: "/",
    icon: "dashboard",
    enabled: true,
    sidebar: true,
    dashboard: true,
    searchable: true,
    order: 1,
    version: "1.0.0",
    permissions: ["view"],
  },
  {
    id: "membership",
    name: "Membership Engine",
    category: "Membership",
    route: "/membership",
    icon: "groups",
    enabled: true,
    sidebar: true,
    dashboard: true,
    searchable: true,
    order: 2,
    version: "1.0.0",
    permissions: ["view", "create", "edit", "delete"],
  },
  {
    id: "member-directory",
    name: "Member Directory",
    category: "Membership",
    route: "/member-directory",
    icon: "badge",
    enabled: true,
    sidebar: true,
    dashboard: true,
    searchable: true,
    order: 2.1,
    version: "1.0.0",
    permissions: ["view"],
  },
  {
    id: "member-verification",
    name: "Member Verification",
    category: "Membership",
    route: "/member-verification",
    icon: "how_to_reg",
    enabled: true,
    sidebar: true,
    dashboard: true,
    searchable: true,
    order: 2.2,
    version: "1.0.0",
    permissions: ["view", "edit"],
  },

  // LEGAL & ADVOCACY
  {
    id: "legal",
    name: "Legal Registry",
    category: "Legal",
    route: "/legal",
    icon: "gavel",
    enabled: true,
    sidebar: true,
    dashboard: true,
    searchable: true,
    order: 3,
    version: "1.0.0",
    permissions: ["view", "create", "edit", "delete"],
  },
  {
    id: "advocate-dashboard",
    name: "Advocate Centre",
    category: "Legal",
    route: "/advocate-dashboard",
    icon: "gavel",
    enabled: true,
    sidebar: true,
    dashboard: true,
    searchable: true,
    order: 3.1,
    version: "1.0.0",
    permissions: ["view"],
  },
  {
    id: "client-portal",
    name: "Client Portal",
    category: "Legal",
    route: "/client-portal",
    icon: "folder",
    enabled: true,
    sidebar: true,
    dashboard: true,
    searchable: true,
    order: 3.2,
    version: "1.0.0",
    permissions: ["view"],
  },
  {
    id: "trust-dashboard",
    name: "Trust Executive",
    category: "Legal",
    route: "/trust-dashboard",
    icon: "account_balance_wallet",
    enabled: true,
    sidebar: true,
    dashboard: true,
    searchable: true,
    order: 3.3,
    version: "1.0.0",
    permissions: ["view"],
  },
  {
    id: "court-calendar",
    name: "Court Calendar",
    category: "Legal",
    route: "/court-calendar",
    icon: "dashboard",
    enabled: true,
    sidebar: true,
    dashboard: true,
    searchable: true,
    order: 3.4,
    version: "1.0.0",
    permissions: ["view"],
  },

  // AI & INTELLIGENCE
  {
    id: "ai-drafter",
    name: "AI Legal Drafter",
    category: "AI",
    route: "/ai-drafter",
    icon: "smart_toy",
    enabled: true,
    sidebar: true,
    dashboard: true,
    searchable: true,
    order: 4,
    version: "1.0.0",
    permissions: ["view"],
  },
  {
    id: "ai",
    name: "AI Assistant",
    category: "AI",
    route: "/ai",
    icon: "smart_toy",
    enabled: true,
    sidebar: true,
    dashboard: true,
    searchable: true,
    order: 4.1,
    version: "1.0.0",
    permissions: ["view"],
  },

  // FINANCE & WALLET
  {
    id: "billing",
    name: "Billing & Revenue",
    category: "Finance",
    route: "/billing",
    icon: "receipt_long",
    enabled: true,
    sidebar: true,
    dashboard: true,
    searchable: true,
    order: 5,
    version: "1.0.0",
    permissions: ["view"],
  },
  {
    id: "finance",
    name: "Finance & Wallet",
    category: "Finance",
    route: "/finance",
    icon: "account_balance_wallet",
    enabled: true,
    sidebar: true,
    dashboard: true,
    searchable: true,
    order: 5.1,
    version: "1.0.0",
    permissions: ["view"],
  },
  {
    id: "payment-management",
    name: "Payment Management",
    category: "Finance",
    route: "/payment-management",
    icon: "account_balance_wallet",
    enabled: true,
    sidebar: true,
    dashboard: true,
    searchable: true,
    order: 5.2,
    version: "1.0.0",
    permissions: ["view"],
  },
  {
    id: "token",
    name: "Token Governance",
    category: "Finance",
    route: "/token",
    icon: "savings",
    enabled: true,
    sidebar: true,
    dashboard: true,
    searchable: true,
    order: 5.3,
    version: "1.0.0",
    permissions: ["view"],
  },

  // DOCUMENTS & RESEARCH
  {
    id: "documents",
    name: "Document Vault",
    category: "Core",
    route: "/documents",
    icon: "folder",
    enabled: true,
    sidebar: true,
    dashboard: true,
    searchable: true,
    order: 6,
    version: "1.0.0",
    permissions: ["view", "upload", "delete"],
  },
  {
    id: "research",
    name: "Research Engine",
    category: "Research",
    route: "/research",
    icon: "science",
    enabled: true,
    sidebar: true,
    dashboard: true,
    searchable: true,
    order: 6.1,
    version: "1.0.0",
    permissions: ["view"],
  },

  // ADMINISTRATION & SYSTEM GOVERNANCE
  {
    id: "administration",
    name: "Administration Desk",
    category: "Admin",
    route: "/administration",
    icon: "admin_panel_settings",
    enabled: true,
    sidebar: true,
    dashboard: true,
    searchable: true,
    order: 7,
    version: "1.0.0",
    permissions: ["view", "admin"],
  },
  {
    id: "governance-center",
    name: "Governance Center",
    category: "Admin",
    route: "/governance-center",
    icon: "verified_user",
    enabled: true,
    sidebar: true,
    dashboard: true,
    searchable: true,
    order: 7.1,
    version: "1.0.0",
    permissions: ["view", "admin"],
  },
  {
    id: "location-master",
    name: "Location Master",
    category: "Admin",
    route: "/location-master",
    icon: "location_on",
    enabled: true,
    sidebar: true,
    dashboard: true,
    searchable: true,
    order: 7.2,
    version: "1.0.0",
    permissions: ["view", "admin"],
  },
  {
    id: "database-config",
    name: "Database Config",
    category: "Admin",
    route: "/database-config",
    icon: "storage",
    enabled: true,
    sidebar: true,
    dashboard: true,
    searchable: true,
    order: 7.3,
    version: "1.0.0",
    permissions: ["view", "admin"],
  },
  {
    id: "api-config",
    name: "API Gateway & Config",
    category: "Admin",
    route: "/api-config",
    icon: "api",
    enabled: true,
    sidebar: true,
    dashboard: true,
    searchable: true,
    order: 7.4,
    version: "1.0.0",
    permissions: ["view", "admin"],
  },
  {
    id: "deployment-center",
    name: "Deployment Center",
    category: "Admin",
    route: "/deployment-center",
    icon: "cloud_upload",
    enabled: true,
    sidebar: true,
    dashboard: true,
    searchable: true,
    order: 7.5,
    version: "1.0.0",
    permissions: ["view", "admin"],
  },
  {
    id: "system-health",
    name: "System Health & Metrics",
    category: "Admin",
    route: "/system-health",
    icon: "monitor_heart",
    enabled: true,
    sidebar: true,
    dashboard: true,
    searchable: true,
    order: 7.6,
    version: "1.0.0",
    permissions: ["view", "admin"],
  },

  // REPORTS & ANALYTICS
  {
    id: "reports",
    name: "Reports Registry",
    category: "Analytics",
    route: "/reports",
    icon: "assessment",
    enabled: true,
    sidebar: true,
    dashboard: true,
    searchable: true,
    order: 8,
    version: "1.0.0",
    permissions: ["view", "create"],
  },
  {
    id: "activity-log",
    name: "Activity & Audit Log",
    category: "Analytics",
    route: "/activity-log",
    icon: "history",
    enabled: true,
    sidebar: true,
    dashboard: true,
    searchable: true,
    order: 8.1,
    version: "1.0.0",
    permissions: ["view"],
  },

  // SYSTEM SETTINGS & NOTIFICATIONS
  {
    id: "settings",
    name: "System Settings",
    category: "System",
    route: "/settings",
    icon: "settings",
    enabled: true,
    sidebar: true,
    dashboard: false,
    searchable: false,
    order: 9,
    version: "1.0.0",
    permissions: ["view", "admin"],
  },
  {
    id: "notifications",
    name: "Notifications",
    category: "System",
    route: "/notifications",
    icon: "notifications",
    enabled: true,
    sidebar: true,
    dashboard: false,
    searchable: false,
    order: 9.1,
    version: "1.0.0",
    permissions: ["view"],
  },
];

export const getAllModules = () => Modules;
export const getEnabledModules = () => Modules.filter((m) => m.enabled);
export const getSidebarModules = () => Modules.filter((m) => m.enabled && m.sidebar);
export const getDashboardModules = () => Modules.filter((m) => m.enabled && m.dashboard);
export const getSearchModules = () => Modules.filter((m) => m.enabled && m.searchable);
export const getModuleById = (id) => Modules.find((m) => m.id === id);

export default Modules;