import { normalizeRoleCode } from "./roles";

export const MODULE_PERMISSION_CATALOG = {
    membership: [
        "membership.view",
        "membership.create",
        "membership.update",
        "membership.delete",
        "membership.restore",
        "membership.export",
        "membership.import",
        "membership.configure",
        "membership.audit.view",
    ],
    approvals: [
        "membership.approve",
        "membership.reject",
        "membership.verify",
        "membership.suspend",
        "membership.reactivate",
        "membership.role.change",
    ],
    finance: [
        "finance.view.all",
        "finance.view.own",
        "finance.accounts.manage",
        "finance.entry.post",
        "finance.entry.delete",
        "finance.vouchers.manage",
        "finance.settings.manage",
        "finance.export",
    ],
    wallet: ["wallet.view", "wallet.credit", "wallet.debit", "wallet.transfer"],
    payments: ["payments.view", "payments.create", "payments.refund", "payments.export"],
    legal: ["legal.view", "legal.create", "legal.update", "legal.delete"],
    documents: [
        "documents.view",
        "documents.upload",
        "documents.download",
        "documents.delete",
        "documents.update",
        "documents.version.manage",
        "documents.categories.manage",
        "documents.folders.manage",
        "documents.audit.view",
        "documents.export",
        "documents.settings.manage",
    ],
    workflow: [
        "workflow.view.all",
        "workflow.view.own",
        "workflow.define",
        "workflow.start",
        "workflow.approve",
        "workflow.reject",
        "workflow.assign",
        "workflow.settings.manage",
    ],
    ai: ["ai.view", "ai.run", "ai.manage"],
    reports: ["reports.view", "reports.export"],
    notifications: [
        "notifications.view",
        "notifications.manage",
        "notifications.templates.manage",
        "notifications.queue.manage",
        "notifications.settings.manage",
    ],
    recovery: ["recovery.request", "recovery.review", "recovery.approve"],
    devices: ["device.view.own", "device.revoke.own", "device.view.all", "device.revoke.any"],
    sessions: [
        "session.view.own",
        "session.revoke.own",
        "session.revoke.others",
        "session.view.all",
        "session.revoke.any",
    ],
};

const ALL_PERMISSIONS = Object.values(MODULE_PERMISSION_CATALOG).flatMap((permissions) => permissions);

const BASE_MEMBER_PERMISSIONS = [
    "membership.view",
    "documents.view",
    "documents.download",
    "notifications.view",
    "device.view.own",
    "device.revoke.own",
    "session.view.own",
    "session.revoke.own",
];

const readAuthorizationConfig = () => {
    if (typeof window === "undefined") return {};
    try {
        const raw = window.localStorage.getItem("icj_settings");
        const parsed = raw ? JSON.parse(raw) : [];
        const root = Array.isArray(parsed) ? parsed[0] : parsed;
        const membership = root?.membership && typeof root.membership === "object" ? root.membership : {};
        const authorization = membership?.authorization && typeof membership.authorization === "object"
            ? membership.authorization
            : {};
        return authorization;
    } catch {
        return {};
    }
};

const mergeRolePermissionMap = (baseMap, configuredMap) => {
    const source = configuredMap && typeof configuredMap === "object" ? configuredMap : {};
    const merged = { ...baseMap };
    Object.entries(source).forEach(([roleCode, permissions]) => {
        if (Array.isArray(permissions)) {
            merged[String(roleCode).toLowerCase()] = permissions;
        }
    });
    return merged;
};

const mergeRouteAccessMap = (baseMap, configuredMap) => {
    const source = configuredMap && typeof configuredMap === "object" ? configuredMap : {};
    const merged = { ...baseMap };
    Object.entries(source).forEach(([roleCode, routes]) => {
        if (Array.isArray(routes)) {
            merged[String(roleCode).toLowerCase()] = routes;
        }
    });
    return merged;
};

export const ROLE_PERMISSION_MAP = {
    super_admin: ["*"],
    system_admin: ["*"],
    admin: [
        "membership.view",
        "membership.create",
        "membership.update",
        "membership.delete",
        "membership.export",
        "membership.import",
        "membership.configure",
        "membership.audit.view",
        "membership.approve",
        "membership.reject",
        "membership.verify",
        "membership.suspend",
        "membership.reactivate",
        "documents.view",
        "documents.download",
        "notifications.view",
        "reports.view",
        "device.view.own",
        "device.revoke.own",
        "session.view.own",
        "session.revoke.own",
    ],
    operator: [
        "membership.view",
        "membership.create",
        "membership.update",
        "documents.view",
        "documents.download",
        "notifications.view",
        "device.view.own",
        "device.revoke.own",
        "session.view.own",
        "session.revoke.own",
    ],
    reviewer: [
        "membership.view",
        "membership.approve",
        "membership.reject",
        "membership.verify",
        "membership.audit.view",
        "documents.view",
        "documents.download",
        "reports.view",
        "notifications.view",
        "device.view.own",
        "device.revoke.own",
        "session.view.own",
        "session.revoke.own",
    ],
    viewer: [
        "membership.view",
        "documents.view",
        "documents.download",
        "notifications.view",
        "reports.view",
        "device.view.own",
        "device.revoke.own",
        "session.view.own",
        "session.revoke.own",
    ],
    organization_admin: [
        ...MODULE_PERMISSION_CATALOG.membership,
        ...MODULE_PERMISSION_CATALOG.finance,
        ...MODULE_PERMISSION_CATALOG.wallet,
        ...MODULE_PERMISSION_CATALOG.payments,
        ...MODULE_PERMISSION_CATALOG.legal,
        ...MODULE_PERMISSION_CATALOG.documents,
        ...MODULE_PERMISSION_CATALOG.workflow,
        ...MODULE_PERMISSION_CATALOG.ai,
        ...MODULE_PERMISSION_CATALOG.reports,
        ...MODULE_PERMISSION_CATALOG.notifications,
        ...MODULE_PERMISSION_CATALOG.recovery,
        ...MODULE_PERMISSION_CATALOG.devices,
        ...MODULE_PERMISSION_CATALOG.sessions,
    ],
    employee: [
        "membership.view",
        "membership.create",
        "membership.update",
        "finance.view.all",
        "finance.entry.post",
        "finance.vouchers.manage",
        "finance.export",
        "wallet.view",
        "wallet.credit",
        "wallet.debit",
        "payments.view",
        "payments.create",
        "legal.view",
        "legal.create",
        "documents.view",
        "documents.upload",
        "documents.download",
        "documents.update",
        "documents.version.manage",
        "documents.categories.manage",
        "documents.folders.manage",
        "documents.audit.view",
        "documents.export",
        "workflow.view.all",
        "workflow.start",
        "workflow.approve",
        "workflow.reject",
        "workflow.assign",
        "ai.view",
        "ai.run",
        "reports.view",
        "reports.export",
        "notifications.view",
        "notifications.templates.manage",
        "notifications.queue.manage",
        "recovery.request",
        "device.view.own",
        "device.revoke.own",
        "session.view.own",
        "session.revoke.own",
    ],
    member: [...BASE_MEMBER_PERMISSIONS, "workflow.view.own", "workflow.start"],
    volunteer: [...BASE_MEMBER_PERMISSIONS, "membership.create", "documents.upload", "recovery.request", "workflow.view.own", "workflow.start"],
    advocate: [...BASE_MEMBER_PERMISSIONS, "legal.view", "legal.create", "legal.update", "documents.upload", "documents.update", "documents.version.manage", "reports.view"],
    arbitrator: [...BASE_MEMBER_PERMISSIONS, "legal.view", "legal.update", "reports.view"],
    mediator: [...BASE_MEMBER_PERMISSIONS, "legal.view", "legal.create", "documents.upload", "documents.update"],
    trustee: [...BASE_MEMBER_PERMISSIONS, "finance.view.all", "wallet.view", "payments.view", "reports.view"],
    district_president: [...BASE_MEMBER_PERMISSIONS, "membership.create", "membership.update", "reports.view", "notifications.manage", "notifications.queue.manage"],
    state_president: [...BASE_MEMBER_PERMISSIONS, "membership.create", "membership.update", "reports.view", "reports.export", "notifications.manage", "notifications.queue.manage"],
    national_executive: [...BASE_MEMBER_PERMISSIONS, "membership.create", "membership.update", "reports.view", "reports.export", "notifications.manage", "notifications.queue.manage", "ai.view"],
    professional_member: [...BASE_MEMBER_PERMISSIONS, "reports.view"],
    support_partner: ["documents.view", "documents.download", "reports.view", "notifications.view", "device.view.own", "device.revoke.own", "session.view.own", "session.revoke.own"],
    help_seeker: ["documents.view", "notifications.view", "device.view.own", "device.revoke.own", "session.view.own", "session.revoke.own"],
    service_applicant: ["documents.view", "notifications.view", "device.view.own", "device.revoke.own", "session.view.own", "session.revoke.own"],
    citizen_applicant: ["documents.view", "notifications.view", "device.view.own", "device.revoke.own", "session.view.own", "session.revoke.own"],
    guest: ["documents.view", "notifications.view", "device.view.own", "device.revoke.own", "session.view.own", "session.revoke.own"],
};

export const ROUTE_ACCESS_MAP = {
    super_admin: ["*"],
    system_admin: ["*"],
    admin: [
        "/",
        "/dashboard",
        "/membership",
        "/members",
        "/member-registration",
        "/member-directory",
        "/member-documents",
        "/member-history",
        "/member-profile",
        "/member-verification",
        "/documents",
        "/notifications",
        "/reports",
        "/settings",
        "/profile",
        "/account-recovery",
    ],
    operator: [
        "/",
        "/dashboard",
        "/membership",
        "/members",
        "/member-registration",
        "/member-directory",
        "/member-documents",
        "/member-profile",
        "/documents",
        "/notifications",
        "/settings",
        "/profile",
        "/account-recovery",
    ],
    reviewer: [
        "/",
        "/dashboard",
        "/membership",
        "/members",
        "/member-directory",
        "/member-verification",
        "/member-history",
        "/member-profile",
        "/documents",
        "/notifications",
        "/reports",
        "/settings",
        "/profile",
        "/account-recovery",
    ],
    viewer: [
        "/",
        "/dashboard",
        "/membership",
        "/members",
        "/member-directory",
        "/member-profile",
        "/documents",
        "/notifications",
        "/reports",
        "/settings",
        "/profile",
        "/account-recovery",
    ],
    organization_admin: [
        "/",
        "/dashboard",
        "/membership",
        "/members",
        "/member-registration",
        "/member-directory",
        "/member-documents",
        "/member-wallet",
        "/member-kyc",
        "/member-identity",
        "/member-certificates",
        "/member-history",
        "/member-activity",
        "/member-settings",
        "/member-card",
        "/member-profile",
        "/identity",
        "/wallet",
        "/finance",
        "/token",
        "/tokens",
        "/donation",
        "/transactions",
        "/legal",
        "/documents",
        "/notifications",
        "/settings",
        "/activity-log",
        "/profile",
        "/ai",
        "/research",
        "/reports",
        "/account-recovery",
    ],
    employee: [
        "/",
        "/dashboard",
        "/membership",
        "/members",
        "/member-registration",
        "/member-directory",
        "/member-documents",
        "/member-wallet",
        "/member-kyc",
        "/member-identity",
        "/member-certificates",
        "/member-history",
        "/member-activity",
        "/member-settings",
        "/member-card",
        "/member-profile",
        "/identity",
        "/wallet",
        "/finance",
        "/token",
        "/tokens",
        "/donation",
        "/transactions",
        "/legal",
        "/documents",
        "/notifications",
        "/settings",
        "/activity-log",
        "/profile",
        "/ai",
        "/research",
        "/reports",
        "/account-recovery",
    ],
    member: [
        "/",
        "/dashboard",
        "/membership",
        "/members",
        "/member-directory",
        "/member-documents",
        "/member-wallet",
        "/member-identity",
        "/member-history",
        "/member-profile",
        "/member-card",
        "/wallet",
        "/documents",
        "/profile",
        "/notifications",
        "/ai",
        "/settings",
        "/account-recovery",
    ],
    volunteer: [
        "/",
        "/dashboard",
        "/membership",
        "/members",
        "/member-directory",
        "/member-documents",
        "/documents",
        "/profile",
        "/notifications",
        "/settings",
        "/account-recovery",
    ],
    advocate: [
        "/",
        "/dashboard",
        "/membership",
        "/members",
        "/member-directory",
        "/member-documents",
        "/member-history",
        "/member-profile",
        "/legal",
        "/documents",
        "/profile",
        "/notifications",
        "/reports",
        "/account-recovery",
    ],
    arbitrator: [
        "/",
        "/dashboard",
        "/membership",
        "/members",
        "/member-directory",
        "/member-documents",
        "/member-history",
        "/member-profile",
        "/legal",
        "/documents",
        "/profile",
        "/notifications",
        "/reports",
        "/account-recovery",
    ],
    mediator: [
        "/",
        "/dashboard",
        "/membership",
        "/members",
        "/member-directory",
        "/member-documents",
        "/member-history",
        "/member-profile",
        "/legal",
        "/documents",
        "/profile",
        "/notifications",
        "/account-recovery",
    ],
    trustee: [
        "/",
        "/dashboard",
        "/membership",
        "/members",
        "/member-directory",
        "/member-documents",
        "/member-profile",
        "/wallet",
        "/finance",
        "/reports",
        "/documents",
        "/profile",
        "/notifications",
        "/account-recovery",
    ],
    district_president: [
        "/",
        "/dashboard",
        "/membership",
        "/members",
        "/member-directory",
        "/member-documents",
        "/member-profile",
        "/documents",
        "/profile",
        "/notifications",
        "/reports",
        "/account-recovery",
    ],
    state_president: [
        "/",
        "/dashboard",
        "/membership",
        "/members",
        "/member-directory",
        "/member-documents",
        "/member-profile",
        "/documents",
        "/profile",
        "/notifications",
        "/reports",
        "/account-recovery",
    ],
    national_executive: [
        "/",
        "/dashboard",
        "/membership",
        "/members",
        "/member-directory",
        "/member-documents",
        "/member-profile",
        "/documents",
        "/profile",
        "/notifications",
        "/reports",
        "/account-recovery",
    ],
    professional_member: [
        "/",
        "/dashboard",
        "/membership",
        "/members",
        "/member-directory",
        "/member-documents",
        "/member-wallet",
        "/member-identity",
        "/member-history",
        "/member-profile",
        "/member-card",
        "/wallet",
        "/documents",
        "/profile",
        "/notifications",
        "/reports",
        "/account-recovery",
    ],
    support_partner: ["/", "/dashboard", "/documents", "/reports", "/notifications", "/profile", "/settings", "/account-recovery"],
    help_seeker: ["/", "/dashboard", "/documents", "/notifications", "/profile", "/settings", "/account-recovery"],
    service_applicant: ["/", "/dashboard", "/documents", "/notifications", "/profile", "/settings", "/account-recovery"],
    citizen_applicant: ["/", "/dashboard", "/documents", "/notifications", "/profile", "/settings", "/account-recovery"],
    guest: ["/", "/dashboard", "/documents", "/notifications", "/profile", "/settings", "/account-recovery"],
};

export const getRolePermissions = (roleCode) => {
    const normalized = normalizeRoleCode(roleCode);
    const configuredMap = mergeRolePermissionMap(
        ROLE_PERMISSION_MAP,
        readAuthorizationConfig().rolePermissions
    );
    return configuredMap[normalized] || configuredMap.member;
};

export const getRouteAccessMap = () =>
    mergeRouteAccessMap(ROUTE_ACCESS_MAP, readAuthorizationConfig().routeAccess);

export const hasPermission = (roleCode, permission) => {
    const permissions = getRolePermissions(roleCode);
    if (permissions.includes("*")) return true;
    return permissions.includes(permission);
};

export const enforcePermission = (roleCode, permission) => {
    if (roleCode && !hasPermission(roleCode, permission)) {
        throw new Error(`Permission Denied: Role '${roleCode}' lacks required permission '${permission}'.`);
    }
    return true;
};

export const hasOrganizationPermission = (organizationPermissions = [], permission = "") => {
    const scoped = Array.isArray(organizationPermissions) ? organizationPermissions : [];
    if (scoped.includes("organization.*")) return true;
    return scoped.includes(permission);
};

export const getAllPermissions = () => [...ALL_PERMISSIONS];
