/**
 * UNIVERSAL 5-COLOR PERMISSION CLASSIFICATION CONSTANTS
 */
export const UNIVERSAL_PERMISSION_COLORS = {
  FREQUENT: {
    code: "FREQUENT",
    label: "Frequent / Operational",
    hex: "#10b981", // Green
    chipColor: "success",
    badgeIcon: "🟢",
    description: "Daily work, active cases, today's hearings, client operations",
  },
  NORMAL: {
    code: "NORMAL",
    label: "Normal / Functional",
    hex: "#f97316", // Orange
    chipColor: "warning",
    badgeIcon: "🟠",
    description: "Reports, secondary workflows, general administration",
  },
  CRITICAL: {
    code: "CRITICAL",
    label: "Critical / Restricted",
    hex: "#ef4444", // Red
    chipColor: "error",
    badgeIcon: "🔴",
    description: "Security, Role & Permission Management, System Configuration, Access Control",
  },
  SYSTEM: {
    code: "SYSTEM",
    label: "System / Reference",
    hex: "#3b82f6", // Blue
    chipColor: "info",
    badgeIcon: "🔵",
    description: "System info, Help, Documentation, Reference data",
  },
  FINANCE: {
    code: "FINANCE",
    label: "Finance / Payment",
    hex: "#8b5cf6", // Violet
    chipColor: "secondary",
    badgeIcon: "🟣",
    description: "Payments, Transactions, Wallet, Accounts, Billing, Refunds",
  },
};

const Modules = [
  // ─── 6 UNIFIED MASTER COMMAND HUBS (VISIBLE IN SIDEBAR) ──────────────────────────
  {
    id: "dashboard",
    name: "📊 मुख्य डैशबोर्ड (Dashboard)",
    category: "Core",
    group: "A",
    route: "/dashboard",
    icon: "dashboard",
    enabled: true,
    sidebar: true,
    dashboard: true,
    searchable: true,
    order: 1,
    colorClassification: UNIVERSAL_PERMISSION_COLORS.FREQUENT,
    version: "2.0.0",
    permissions: ["view"],
  },
  {
    id: "membership-hub",
    name: "👥 [GROUP A] सदस्यता केंद्र (Codes A1-A6)",
    category: "Membership",
    group: "A",
    route: "/membership-hub",
    icon: "groups",
    enabled: true,
    sidebar: true,
    dashboard: true,
    searchable: true,
    order: 2,
    colorClassification: UNIVERSAL_PERMISSION_COLORS.FREQUENT,
    version: "2.0.0",
    permissions: ["view"],
  },
  {
    id: "legal-workspace",
    name: "⚖️ [GROUP B] विधिक कार्यक्षेत्र (Codes B1-B6)",
    category: "Legal",
    group: "B",
    route: "/legal-workspace",
    icon: "gavel",
    enabled: true,
    sidebar: true,
    dashboard: true,
    searchable: true,
    order: 3,
    colorClassification: UNIVERSAL_PERMISSION_COLORS.FREQUENT,
    version: "2.0.0",
    permissions: ["view"],
  },
  {
    id: "ai-legal-hub",
    name: "🤖 [GROUP C] AI ड्राफ्ट व रिसर्च (Codes C1-C4)",
    category: "AI",
    group: "C",
    route: "/ai-legal-hub",
    icon: "smart_toy",
    enabled: true,
    sidebar: true,
    dashboard: true,
    searchable: true,
    order: 4,
    colorClassification: UNIVERSAL_PERMISSION_COLORS.SYSTEM,
    version: "2.0.0",
    permissions: ["view"],
  },
  {
    id: "finance-hub",
    name: "💳 [GROUP D] वित्त एवं वॉलेट (Codes D1-D6)",
    category: "Finance",
    group: "D",
    route: "/finance-hub",
    icon: "account_balance_wallet",
    enabled: true,
    sidebar: true,
    dashboard: true,
    searchable: true,
    order: 5,
    colorClassification: UNIVERSAL_PERMISSION_COLORS.FINANCE,
    version: "2.0.0",
    permissions: ["view"],
  },
  {
    id: "support-hub",
    name: "🎧 [GROUP E] हेल्पडेस्क व सहायता (Codes E1-E3)",
    category: "Support",
    group: "E",
    route: "/support-hub",
    icon: "support_agent",
    enabled: true,
    sidebar: true,
    dashboard: true,
    searchable: true,
    order: 6,
    colorClassification: UNIVERSAL_PERMISSION_COLORS.NORMAL,
    version: "2.0.0",
    permissions: ["view"],
  },
  {
    id: "admin-control-hub",
    name: "🛡️ [GROUP F] प्रशासन नियंत्रण (Codes F1-F6)",
    category: "Admin",
    group: "F",
    route: "/admin-control-hub",
    icon: "admin_panel_settings",
    enabled: true,
    sidebar: true,
    dashboard: true,
    searchable: true,
    order: 7,
    colorClassification: UNIVERSAL_PERMISSION_COLORS.CRITICAL,
    version: "2.0.0",
    permissions: ["view", "admin"],
  },

  // ─── SECONDARY SUB-MODULES (ACCESSIBLE VIA HUBS / DIRECT ROUTES) ───────────────
  {
    id: "membership",
    name: "Membership Engine",
    category: "Membership",
    group: "A",
    route: "/membership",
    icon: "groups",
    enabled: true,
    sidebar: false,
    dashboard: true,
    searchable: true,
    order: 10,
    colorClassification: UNIVERSAL_PERMISSION_COLORS.FREQUENT,
    version: "1.0.0",
    permissions: ["view", "create", "edit", "delete"],
  },
  {
    id: "member-directory",
    name: "Mem. Directory",
    category: "Membership",
    group: "A",
    route: "/member-directory",
    icon: "badge",
    enabled: true,
    sidebar: false,
    dashboard: true,
    searchable: true,
    order: 11,
    colorClassification: UNIVERSAL_PERMISSION_COLORS.FREQUENT,
    version: "1.0.0",
    permissions: ["view"],
  },
  {
    id: "member-verification",
    name: "Mem. Verif.",
    category: "Membership",
    group: "A",
    route: "/member-verification",
    icon: "how_to_reg",
    enabled: true,
    sidebar: false,
    dashboard: true,
    searchable: true,
    order: 12,
    colorClassification: UNIVERSAL_PERMISSION_COLORS.FREQUENT,
    version: "1.0.0",
    permissions: ["view", "edit"],
  },
  {
    id: "member-profile",
    name: "Mem. Profile",
    category: "Membership",
    group: "A",
    route: "/member-profile",
    icon: "badge",
    enabled: true,
    sidebar: false,
    dashboard: true,
    searchable: true,
    order: 13,
    colorClassification: UNIVERSAL_PERMISSION_COLORS.NORMAL,
    version: "1.0.0",
    permissions: ["view", "edit"],
  },
  {
    id: "legal",
    name: "Legal Registry",
    category: "Legal",
    group: "A",
    route: "/legal",
    icon: "gavel",
    enabled: true,
    sidebar: false,
    dashboard: true,
    searchable: true,
    order: 14,
    colorClassification: UNIVERSAL_PERMISSION_COLORS.FREQUENT,
    version: "1.0.0",
    permissions: ["view", "create", "edit", "delete"],
  },
  {
    id: "advocate-dashboard",
    name: "Advocate Desk",
    category: "Legal",
    group: "A",
    route: "/advocate-dashboard",
    icon: "gavel",
    enabled: true,
    sidebar: false,
    dashboard: true,
    searchable: true,
    order: 15,
    colorClassification: UNIVERSAL_PERMISSION_COLORS.FREQUENT,
    version: "1.0.0",
    permissions: ["view"],
  },
  {
    id: "client-portal",
    name: "Client Portal",
    category: "Legal",
    group: "A",
    route: "/client-portal",
    icon: "folder",
    enabled: true,
    sidebar: false,
    dashboard: true,
    searchable: true,
    order: 16,
    colorClassification: UNIVERSAL_PERMISSION_COLORS.FREQUENT,
    version: "1.0.0",
    permissions: ["view"],
  },
  {
    id: "court-calendar",
    name: "Court Calendar",
    category: "Legal",
    group: "A",
    route: "/court-calendar",
    icon: "dashboard",
    enabled: true,
    sidebar: false,
    dashboard: true,
    searchable: true,
    order: 17,
    colorClassification: UNIVERSAL_PERMISSION_COLORS.FREQUENT,
    version: "1.0.0",
    permissions: ["view"],
  },
  {
    id: "ai-drafter",
    name: "AI Legal Drafter",
    category: "AI",
    group: "A",
    route: "/ai-drafter",
    icon: "smart_toy",
    enabled: true,
    sidebar: false,
    dashboard: true,
    searchable: true,
    order: 18,
    colorClassification: UNIVERSAL_PERMISSION_COLORS.SYSTEM,
    version: "1.0.0",
    permissions: ["view"],
  },
  {
    id: "billing",
    name: "Billing & Rev.",
    category: "Finance",
    group: "A",
    route: "/billing",
    icon: "receipt_long",
    enabled: true,
    sidebar: false,
    dashboard: true,
    searchable: true,
    order: 19,
    colorClassification: UNIVERSAL_PERMISSION_COLORS.FINANCE,
    version: "1.0.0",
    permissions: ["view"],
  },
  {
    id: "finance",
    name: "Finance & Wallet",
    category: "Finance",
    group: "A",
    route: "/finance",
    icon: "account_balance_wallet",
    enabled: true,
    sidebar: false,
    dashboard: true,
    searchable: true,
    order: 20,
    colorClassification: UNIVERSAL_PERMISSION_COLORS.FINANCE,
    version: "1.0.0",
    permissions: ["view"],
  },
  {
    id: "payment-management",
    name: "Payment Mgmt.",
    category: "Finance",
    group: "A",
    route: "/payment-management",
    icon: "account_balance_wallet",
    enabled: true,
    sidebar: false,
    dashboard: true,
    searchable: true,
    order: 21,
    colorClassification: UNIVERSAL_PERMISSION_COLORS.FINANCE,
    version: "1.0.0",
    permissions: ["view"],
  },
  {
    id: "token",
    name: "Token Gov.",
    category: "Finance",
    group: "A",
    route: "/token",
    icon: "savings",
    enabled: true,
    sidebar: false,
    dashboard: true,
    searchable: true,
    order: 22,
    colorClassification: UNIVERSAL_PERMISSION_COLORS.FINANCE,
    version: "1.0.0",
    permissions: ["view"],
  },
  {
    id: "documents",
    name: "Document Vault",
    category: "Core",
    group: "A",
    route: "/documents",
    icon: "folder",
    enabled: true,
    sidebar: false,
    dashboard: true,
    searchable: true,
    order: 23,
    colorClassification: UNIVERSAL_PERMISSION_COLORS.FREQUENT,
    version: "1.0.0",
    permissions: ["view", "upload", "delete"],
  },
  {
    id: "trust-dashboard",
    name: "Trust Executive",
    category: "Legal",
    group: "B",
    route: "/trust-dashboard",
    icon: "account_balance_wallet",
    enabled: true,
    sidebar: false,
    dashboard: true,
    searchable: true,
    order: 24,
    colorClassification: UNIVERSAL_PERMISSION_COLORS.FREQUENT,
    version: "1.0.0",
    permissions: ["view"],
  },
  {
    id: "ai",
    name: "AI Assistant",
    category: "AI",
    group: "B",
    route: "/ai",
    icon: "smart_toy",
    enabled: true,
    sidebar: false,
    dashboard: true,
    searchable: true,
    order: 25,
    colorClassification: UNIVERSAL_PERMISSION_COLORS.SYSTEM,
    version: "1.0.0",
    permissions: ["view"],
  },
  {
    id: "research",
    name: "Research Engine",
    category: "Research",
    group: "B",
    route: "/research",
    icon: "science",
    enabled: true,
    sidebar: false,
    dashboard: true,
    searchable: true,
    order: 26,
    colorClassification: UNIVERSAL_PERMISSION_COLORS.SYSTEM,
    version: "1.0.0",
    permissions: ["view"],
  },
  {
    id: "administration",
    name: "Admin. Desk",
    category: "Admin",
    group: "B",
    route: "/administration",
    icon: "admin_panel_settings",
    enabled: true,
    sidebar: false,
    dashboard: true,
    searchable: true,
    order: 27,
    colorClassification: UNIVERSAL_PERMISSION_COLORS.CRITICAL,
    version: "1.0.0",
    permissions: ["view", "edit", "delete"],
  },
  {
    id: "security-compliance",
    name: "Security & Roles",
    category: "Admin",
    group: "B",
    route: "/security-compliance",
    icon: "verified_user",
    enabled: true,
    sidebar: false,
    dashboard: true,
    searchable: true,
    order: 28,
    colorClassification: UNIVERSAL_PERMISSION_COLORS.CRITICAL,
    version: "1.0.0",
    permissions: ["view", "edit"],
  },
  {
    id: "advocate-directory",
    name: "Advocate Directory",
    category: "Admin",
    group: "B",
    route: "/advocate-directory",
    icon: "badge",
    enabled: true,
    sidebar: false,
    dashboard: true,
    searchable: true,
    order: 29,
    colorClassification: UNIVERSAL_PERMISSION_COLORS.FREQUENT,
    version: "1.0.0",
    permissions: ["view"],
  },
  {
    id: "feature-control",
    name: "Feature & Fee Control",
    category: "Admin",
    group: "B",
    route: "/feature-control",
    icon: "settings",
    enabled: true,
    sidebar: false,
    dashboard: true,
    searchable: true,
    order: 30,
    colorClassification: UNIVERSAL_PERMISSION_COLORS.NORMAL,
    version: "1.0.0",
    permissions: ["view", "edit"],
  },
  {
    id: "governance-center",
    name: "Gov. Center",
    category: "Admin",
    group: "B",
    route: "/governance-center",
    icon: "verified_user",
    enabled: true,
    sidebar: false,
    dashboard: true,
    searchable: true,
    order: 31,
    colorClassification: UNIVERSAL_PERMISSION_COLORS.CRITICAL,
    version: "1.0.0",
    permissions: ["view", "admin"],
  },
  {
    id: "location-master",
    name: "Loc. Master",
    category: "Admin",
    group: "B",
    route: "/location-master",
    icon: "location_on",
    enabled: true,
    sidebar: false,
    dashboard: true,
    searchable: true,
    order: 32,
    colorClassification: UNIVERSAL_PERMISSION_COLORS.NORMAL,
    version: "1.0.0",
    permissions: ["view", "admin"],
  },
  {
    id: "database-config",
    name: "DB Config",
    category: "Admin",
    group: "B",
    route: "/database-config",
    icon: "storage",
    enabled: true,
    sidebar: false,
    dashboard: true,
    searchable: true,
    order: 33,
    colorClassification: UNIVERSAL_PERMISSION_COLORS.CRITICAL,
    version: "1.0.0",
    permissions: ["view", "admin"],
  },
  {
    id: "api-config",
    name: "API Gateway",
    category: "Admin",
    group: "B",
    route: "/api-config",
    icon: "api",
    enabled: true,
    sidebar: false,
    dashboard: true,
    searchable: true,
    order: 34,
    colorClassification: UNIVERSAL_PERMISSION_COLORS.CRITICAL,
    version: "1.0.0",
    permissions: ["view", "admin"],
  },
  {
    id: "deployment-center",
    name: "Deploy Center",
    category: "Admin",
    group: "B",
    route: "/deployment-center",
    icon: "cloud_upload",
    enabled: true,
    sidebar: false,
    dashboard: true,
    searchable: true,
    order: 35,
    colorClassification: UNIVERSAL_PERMISSION_COLORS.CRITICAL,
    version: "1.0.0",
    permissions: ["view", "admin"],
  },
  {
    id: "system-health",
    name: "System Health",
    category: "Admin",
    group: "B",
    route: "/system-health",
    icon: "monitor_heart",
    enabled: true,
    sidebar: false,
    dashboard: true,
    searchable: true,
    order: 36,
    colorClassification: UNIVERSAL_PERMISSION_COLORS.SYSTEM,
    version: "1.0.0",
    permissions: ["view", "admin"],
  },
  {
    id: "reports",
    name: "Reports Registry",
    category: "Analytics",
    group: "B",
    route: "/reports",
    icon: "assessment",
    enabled: true,
    sidebar: false,
    dashboard: true,
    searchable: true,
    order: 37,
    colorClassification: UNIVERSAL_PERMISSION_COLORS.NORMAL,
    version: "1.0.0",
    permissions: ["view", "create"],
  },
  {
    id: "activity-log",
    name: "Activity & Audit Log",
    category: "Analytics",
    group: "B",
    route: "/activity-log",
    icon: "history",
    enabled: true,
    sidebar: false,
    dashboard: true,
    searchable: true,
    order: 38,
    colorClassification: UNIVERSAL_PERMISSION_COLORS.NORMAL,
    version: "1.0.0",
    permissions: ["view"],
  },
  {
    id: "settings",
    name: "System Settings",
    category: "System",
    group: "B",
    route: "/settings",
    icon: "settings",
    enabled: true,
    sidebar: false,
    dashboard: false,
    searchable: false,
    order: 39,
    colorClassification: UNIVERSAL_PERMISSION_COLORS.CRITICAL,
    version: "1.0.0",
    permissions: ["view", "admin"],
  },
  {
    id: "notifications",
    name: "Notifications",
    category: "System",
    group: "B",
    route: "/notifications",
    icon: "notifications",
    enabled: true,
    sidebar: false,
    dashboard: false,
    searchable: false,
    order: 40,
    colorClassification: UNIVERSAL_PERMISSION_COLORS.SYSTEM,
    version: "1.0.0",
    permissions: ["view"],
  },
];

export const getAllModules = () => Modules;
export const getEnabledModules = () => Modules.filter((m) => m.enabled);
export const getSidebarModules = () => Modules.filter((m) => m.enabled && m.sidebar);
export const getGroupAModules = () => Modules.filter((m) => m.enabled && m.group === "A");
export const getGroupBModules = () => Modules.filter((m) => m.enabled && m.group === "B");
export const getDashboardModules = () => Modules.filter((m) => m.enabled && m.dashboard);
export const getSearchModules = () => Modules.filter((m) => m.enabled && m.searchable);
export const getModuleById = (id) => Modules.find((m) => m.id === id);

export const COLOR_SAFETY_WEIGHTS = {
  FREQUENT: 1, // 🟢 Green
  SYSTEM: 2,   // 🔵 Blue
  FINANCE: 3,  // 🟣 Violet
  NORMAL: 4,   // 🟠 Orange
  CRITICAL: 5, // 🔴 Red (Strictly at bottom)
};

export const ROLE_MODULE_PRIORITY = {
  client: [
    "dashboard", "legal-workspace", "membership-hub", "ai-legal-hub",
    "finance-hub", "support-hub"
  ],
  advocate: [
    "dashboard", "legal-workspace", "ai-legal-hub", "membership-hub",
    "finance-hub", "support-hub"
  ],
  admin: [
    "dashboard", "legal-workspace", "membership-hub", "finance-hub",
    "ai-legal-hub", "support-hub", "admin-control-hub"
  ],
  super_admin: [
    "dashboard", "admin-control-hub", "legal-workspace", "membership-hub",
    "finance-hub", "ai-legal-hub", "support-hub"
  ]
};

export const MODULE_ROLE_ACCESS = {
  "membership-hub": ["admin", "employee", "advocate", "member", "client"],
  "legal-workspace": ["advocate", "admin", "client", "member"],
  "ai-legal-hub": ["advocate", "admin", "client", "member"],
  "finance-hub": ["admin", "advocate", "client", "member"],
  "support-hub": ["admin", "advocate", "client", "member", "employee"],
  "admin-control-hub": ["admin", "super_admin"],
  
  membership: ["admin", "employee"],
  "member-directory": ["admin", "employee"],
  "member-verification": ["admin", "employee"],
  "activity-log": ["admin", "employee"],
  "advocate-dashboard": ["advocate", "admin"],
  "client-portal": ["member", "client", "admin"],
  billing: ["admin", "advocate"],
  administration: ["admin"],
  "security-compliance": ["admin"],
  "advocate-directory": ["admin"],
  "feature-control": ["admin"],
  "governance-center": ["admin"],
  "location-master": ["admin"],
  "database-config": ["admin"],
  "api-config": ["admin"],
  "deployment-center": ["admin"],
  "system-health": ["admin"],
  "trust-dashboard": ["admin"],
  "payment-management": ["admin"],
  finance: ["admin"],
  reports: ["admin"],
  settings: ["admin"],
};

const ADMIN_ROLES = ["admin", "super_admin", "superadmin"];

export const canRoleAccessModule = (roleKey, moduleId) => {
  const allowed = MODULE_ROLE_ACCESS[moduleId];
  if (!allowed) return true;
  const role = String(roleKey || "").toLowerCase();
  if (allowed.includes(role)) return true;
  return allowed.includes("admin") && ADMIN_ROLES.includes(role);
};

export const getRoleOrderedModules = (roleKey = "member") => {
  const normalized = String(roleKey).toLowerCase();
  let priorityList = ROLE_MODULE_PRIORITY[normalized];
  if (!priorityList) {
    if (normalized.includes("super")) priorityList = ROLE_MODULE_PRIORITY.super_admin;
    else if (normalized.includes("admin")) priorityList = ROLE_MODULE_PRIORITY.admin;
    else if (normalized.includes("advocate")) priorityList = ROLE_MODULE_PRIORITY.advocate;
    else priorityList = ROLE_MODULE_PRIORITY.client;
  }

  // Only return modules where sidebar is true
  const enabled = getSidebarModules().filter((m) => canRoleAccessModule(normalized, m.id));

  return [...enabled].sort((a, b) => {
    // Primary: Role Priority
    const idxA = priorityList.indexOf(a.id);
    const idxB = priorityList.indexOf(b.id);
    const posA = idxA !== -1 ? idxA : 999;
    const posB = idxB !== -1 ? idxB : 999;

    if (posA !== posB) {
      return posA - posB;
    }

    return (a.order || 99) - (b.order || 99);
  });
};

export default Modules;