-- ============================================================
-- ICJ Enterprise Platform
-- Migration: Create core module tables
-- Date: 2026-07-30
-- ============================================================

create table if not exists public.members (
  id bigint generated by default as identity primary key,
  member_id text unique,
  name text not null,
  email text,
  mobile text,
  whatsapp text,
  member_type text,
  profession text,
  organisation text,
  gender text,
  dob date,
  aadhar text,
  pan text,
  gst text,
  address text,
  city text,
  district text,
  state text,
  pincode text,
  verification_status text default 'Pending',
  member_level text default 'BASIC',
  registration_date timestamp with time zone default timezone('utc'::text, now()),
  valid_till timestamp with time zone,
  remarks text,
  experience text,
  wallet_balance numeric default 0,
  token_balance numeric default 0,
  status text default 'Active',
  profile_photo text,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

create table if not exists public.wallets (
  id bigint generated by default as identity primary key,
  member_id text,
  balance numeric default 0,
  currency text default 'INR',
  status text default 'Active',
  created_at timestamp with time zone default timezone('utc'::text, now())
);

create table if not exists public.tokens (
  id bigint generated by default as identity primary key,
  token_no text unique,
  member_id text,
  amount numeric default 0,
  type text,
  status text default 'Active',
  created_at timestamp with time zone default timezone('utc'::text, now())
);

create table if not exists public.donations (
  id bigint generated by default as identity primary key,
  receipt_no text unique,
  donor_name text,
  member_id text,
  amount numeric default 0,
  payment_mode text,
  status text default 'Received',
  created_at timestamp with time zone default timezone('utc'::text, now())
);

create table if not exists public.legal_cases (
  id bigint generated by default as identity primary key,
  case_number text unique,
  title text,
  client_name text,
  advocate_name text,
  court_name text,
  status text default 'Pending',
  next_hearing date,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

create table if not exists public.documents (
  id bigint generated by default as identity primary key,
  document_no text unique,
  title text,
  category text,
  owner text,
  file_name text,
  file_type text,
  file_path text,
  file_url text,
  status text default 'Active',
  created_at timestamp with time zone default timezone('utc'::text, now())
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  title text,
  message text,
  type text,
  status text default 'Unread',
  read_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  report_no text unique,
  title text,
  category text,
  description text,
  created_by text,
  status text default 'Generated',
  created_at timestamp with time zone default timezone('utc'::text, now())
);

create table if not exists public.system_settings (
  id int primary key,
  enable_notifications boolean default true,
  enable_audit_log boolean default true,
  compact_view boolean default false,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

create index if not exists members_member_id_idx on public.members(member_id);
create index if not exists members_email_idx on public.members(email);
create index if not exists wallets_member_id_idx on public.wallets(member_id);
create index if not exists tokens_member_id_idx on public.tokens(member_id);
create index if not exists donations_member_id_idx on public.donations(member_id);
create index if not exists legal_cases_case_number_idx on public.legal_cases(case_number);
create index if not exists documents_document_no_idx on public.documents(document_no);
create index if not exists reports_report_no_idx on public.reports(report_no);
