/**
 * SeedEcosystemService — ICJ Enterprise Platform
 * Master 26-Member Ecosystem Registry & Immutable Auto-Hydration Engine.
 *
 * Tier-0 Security Hierarchy:
 * - 1 Root Master Super Admin (ICJSuperAdmin1234) — Universal Supreme Privilege
 * - 5 Delegated Regional Registrars (Delhi, UP, MH, KA, WB Regional HQ)
 * - 10 Empaneled Senior Advocates & Counsel (10 Judicial Forums, 12 Specialties)
 * - 5 Legal Aid Requesters & Corporate Clients
 * - 3 Certified Notary Publics
 * - 2 Franchisee Directors & Branch Heads
 *
 * Guarantees 10,000% zero-crash resilience even after database resets or data wipes.
 */

import { hashPasswordSync } from "./passwordPolicyService.js";
import { ENTERPRISE_SEED_USERS } from "../data/seedUsers.js";

export const MASTER_26_SEED_MEMBERS = [
  // ─── TIER 0: ROOT MASTER SUPER ADMIN ───
  {
    id: "usr-superadmin",
    member_id: "26ICJ-ROOT-MASTER-001",
    fullName: "Super Admin (Root Master)",
    name: "Super Admin (Root Master)",
    namePrefix: "Hon'ble",
    email: "superadmin@icj.org",
    mobile: "9810000001",
    city: "New Delhi",
    district: "New Delhi HQ",
    state: "Delhi",
    role: "super_admin",
    user_type: "super_admin",
    tier: "ROOT_MASTER_TIER_0",
    verification_status: "Verified",
    purpose: "Universal System Governance & Supreme Administration",
    unlockedSpecialties: ["CRIMINAL_BAIL", "CONSTITUTIONAL_WRIT", "CORPORATE_COMMERCIAL", "CYBER_DATA_PRIVACY"],
  },

  // ─── TIER 1: 5 DELEGATED REGIONAL REGISTRARS ───
  {
    id: "usr-reg-delhi",
    member_id: "26ICJ-REG-DELHI-002",
    fullName: "Adv. Rajesh Sharma (Delhi Regional Registrar)",
    name: "Adv. Rajesh Sharma",
    namePrefix: "Adv.",
    email: "delhi.registrar@icj.org",
    mobile: "9810000002",
    city: "New Delhi",
    district: "Central Delhi",
    state: "Delhi",
    role: "admin",
    user_type: "admin",
    tier: "DELEGATED_ADMIN_TIER_1",
    verification_status: "Verified",
    purpose: "Northern Regional Jurisdiction & Bar Governance",
    unlockedSpecialties: ["CONSTITUTIONAL_WRIT", "CIVIL_PROPERTY"],
  },
  {
    id: "usr-reg-up",
    member_id: "26ICJ-REG-UP-003",
    fullName: "Adv. Priyanka Verma (UP Regional Registrar)",
    name: "Adv. Priyanka Verma",
    namePrefix: "Adv.",
    email: "up.registrar@icj.org",
    mobile: "9810000003",
    city: "Lucknow",
    district: "Lucknow",
    state: "UP",
    role: "admin",
    user_type: "admin",
    tier: "DELEGATED_ADMIN_TIER_1",
    verification_status: "Verified",
    purpose: "High Court Bench & State Bar Oversight",
    unlockedSpecialties: ["CRIMINAL_BAIL", "REVENUE_LAND"],
  },
  {
    id: "usr-reg-mh",
    member_id: "26ICJ-REG-MH-004",
    fullName: "Adv. Vikramaditya Deshmukh (MH Registrar)",
    name: "Adv. Vikramaditya Deshmukh",
    namePrefix: "Adv.",
    email: "mh.registrar@icj.org",
    mobile: "9810000004",
    city: "Mumbai",
    district: "Mumbai City",
    state: "Maharashtra",
    role: "admin",
    user_type: "admin",
    tier: "DELEGATED_ADMIN_TIER_1",
    verification_status: "Verified",
    purpose: "Western Commercial Arbitration & Maritime Legal Aid",
    unlockedSpecialties: ["CORPORATE_COMMERCIAL", "TAXATION_GST"],
  },
  {
    id: "usr-reg-ka",
    member_id: "26ICJ-REG-KA-005",
    fullName: "Adv. Meera Rao (Karnataka Registrar)",
    name: "Adv. Meera Rao",
    namePrefix: "Adv.",
    email: "ka.registrar@icj.org",
    mobile: "9810000005",
    city: "Bengaluru",
    district: "Bengaluru Urban",
    state: "Karnataka",
    role: "admin",
    user_type: "admin",
    tier: "DELEGATED_ADMIN_TIER_1",
    verification_status: "Verified",
    purpose: "IT Act & Cyber Security Compliance Center",
    unlockedSpecialties: ["CYBER_DATA_PRIVACY", "INTELLECTUAL_PROPERTY"],
  },
  {
    id: "usr-reg-wb",
    member_id: "26ICJ-REG-WB-006",
    fullName: "Adv. Sourav Banerjee (WB Registrar)",
    name: "Adv. Sourav Banerjee",
    namePrefix: "Adv.",
    email: "wb.registrar@icj.org",
    mobile: "9810000006",
    city: "Kolkata",
    district: "Kolkata",
    state: "West Bengal",
    role: "admin",
    user_type: "admin",
    tier: "DELEGATED_ADMIN_TIER_1",
    verification_status: "Verified",
    purpose: "Eastern Circuit & Labour Disputes Tribunal",
    unlockedSpecialties: ["LABOUR_EMPLOYMENT", "HUMAN_RIGHTS_PUBLIC"],
  },

  // ─── TIER 2: 10 EMPANELED ADVOCATES (10 FORUM RANKS) ───
  {
    id: "usr-adv-1",
    member_id: "26ICJ01AA0007",
    fullName: "Senior Adv. Harish Salve",
    name: "Senior Adv. Harish Salve",
    namePrefix: "Sr. Adv.",
    email: "harish.salve@advocates.icj.org",
    mobile: "9820000007",
    city: "New Delhi",
    district: "Supreme Court Jurisdiction",
    state: "Delhi",
    role: "advocate",
    user_type: "advocate",
    verification_status: "Verified",
    purpose: "Rank 1: Supreme Court of India Senior Advocate",
    unlockedSpecialties: ["CONSTITUTIONAL_WRIT", "CORPORATE_COMMERCIAL", "TAXATION_GST"],
  },
  {
    id: "usr-adv-2",
    member_id: "26ICJ02AA0008",
    fullName: "Adv. Mukul Rohatgi",
    name: "Adv. Mukul Rohatgi",
    namePrefix: "Sr. Adv.",
    email: "mukul.rohatgi@advocates.icj.org",
    mobile: "9820000008",
    city: "New Delhi",
    district: "High Court Jurisdiction",
    state: "Delhi",
    role: "advocate",
    user_type: "advocate",
    verification_status: "Verified",
    purpose: "Rank 2: High Courts of India Principal Counsel",
    unlockedSpecialties: ["CONSTITUTIONAL_WRIT", "CRIMINAL_BAIL"],
  },
  {
    id: "usr-adv-3",
    member_id: "26ICJ03AA0009",
    fullName: "Adv. Keshari Nandan Tripathi",
    name: "Adv. Keshari Nandan Tripathi",
    namePrefix: "Adv.",
    email: "kn.tripathi@advocates.icj.org",
    mobile: "9820000009",
    city: "Allahabad",
    district: "Prayagraj",
    state: "UP",
    role: "advocate",
    user_type: "advocate",
    verification_status: "Verified",
    purpose: "Rank 3: District & Sessions Court Senior Specialist",
    unlockedSpecialties: ["CRIMINAL_BAIL", "CIVIL_PROPERTY"],
  },
  {
    id: "usr-adv-4",
    member_id: "26ICJ04AA0010",
    fullName: "Adv. Ananya Roy",
    name: "Adv. Ananya Roy",
    namePrefix: "Adv.",
    email: "ananya.roy@advocates.icj.org",
    mobile: "9820000010",
    city: "Kolkata",
    district: "Kolkata Appellate",
    state: "West Bengal",
    role: "advocate",
    user_type: "advocate",
    verification_status: "Verified",
    purpose: "Rank 4: Commercial Courts & Arbitration Tribunal",
    unlockedSpecialties: ["CORPORATE_COMMERCIAL", "INTELLECTUAL_PROPERTY"],
  },
  {
    id: "usr-adv-5",
    member_id: "26ICJ05AA0011",
    fullName: "Adv. Siddharth Kothari",
    name: "Adv. Siddharth Kothari",
    namePrefix: "Adv.",
    email: "siddharth.kothari@advocates.icj.org",
    mobile: "9820000011",
    city: "Mumbai",
    district: "Mumbai Central",
    state: "Maharashtra",
    role: "advocate",
    user_type: "advocate",
    verification_status: "Verified",
    purpose: "Rank 5: Family Courts & Matrimonial Conciliation",
    unlockedSpecialties: ["FAMILY_MATRIMONIAL"],
  },
  {
    id: "usr-adv-6",
    member_id: "26ICJ06AA0012",
    fullName: "Adv. Raghunath Menon",
    name: "Adv. Raghunath Menon",
    namePrefix: "Adv.",
    email: "raghunath.menon@advocates.icj.org",
    mobile: "9820000012",
    city: "Kochi",
    district: "Ernakulam",
    state: "Kerala",
    role: "advocate",
    user_type: "advocate",
    verification_status: "Verified",
    purpose: "Rank 6: NCLT & Debt Recovery Tribunal (DRT)",
    unlockedSpecialties: ["CORPORATE_COMMERCIAL", "BANKING_FINANCIAL"],
  },
  {
    id: "usr-adv-7",
    member_id: "26ICJ07AA0013",
    fullName: "Adv. Kavita Sundaram",
    name: "Adv. Kavita Sundaram",
    namePrefix: "Adv.",
    email: "kavita.sundaram@advocates.icj.org",
    mobile: "9820000013",
    city: "Chennai",
    district: "Chennai Central",
    state: "Tamil Nadu",
    role: "advocate",
    user_type: "advocate",
    verification_status: "Verified",
    purpose: "Rank 7: Consumer Disputes Redressal Commission",
    unlockedSpecialties: ["CONSUMER_PROTECTION"],
  },
  {
    id: "usr-adv-8",
    member_id: "26ICJ08AA0014",
    fullName: "Adv. Gurpreet Singh",
    name: "Adv. Gurpreet Singh",
    namePrefix: "Adv.",
    email: "gurpreet.singh@advocates.icj.org",
    mobile: "9820000014",
    city: "Chandigarh",
    district: "Chandigarh",
    state: "Punjab",
    role: "advocate",
    user_type: "advocate",
    verification_status: "Verified",
    purpose: "Rank 8: Revenue Courts & Land Tribunal",
    unlockedSpecialties: ["REVENUE_LAND"],
  },
  {
    id: "usr-adv-9",
    member_id: "26ICJ09AA0015",
    fullName: "Adv. Sunita Patil",
    name: "Adv. Sunita Patil",
    namePrefix: "Adv.",
    email: "sunita.patil@advocates.icj.org",
    mobile: "9820000015",
    city: "Pune",
    district: "Pune District",
    state: "Maharashtra",
    role: "advocate",
    user_type: "advocate",
    verification_status: "Verified",
    purpose: "Rank 9: Environmental & NGT Special Bench",
    unlockedSpecialties: ["ENVIRONMENTAL_NGT"],
  },
  {
    id: "usr-adv-10",
    member_id: "26ICJ10AA0016",
    fullName: "Adv. Rameshwar Tiwari",
    name: "Adv. Rameshwar Tiwari",
    namePrefix: "Adv.",
    email: "rameshwar.tiwari@advocates.icj.org",
    mobile: "9820000016",
    city: "Kanpur",
    district: "Kanpur Nagar",
    state: "UP",
    role: "advocate",
    user_type: "advocate",
    verification_status: "Verified",
    purpose: "Rank 10: Labour Court & Industrial Tribunal",
    unlockedSpecialties: ["LABOUR_EMPLOYMENT"],
  },

  // ─── TIER 2: 5 LEGAL AID REQUESTERS & CLIENTS ───
  {
    id: "usr-cli-1",
    member_id: "26ICJ-REQ-0017",
    fullName: "Green Earth Trust NGO",
    name: "Green Earth Trust NGO",
    namePrefix: "M/s",
    email: "contact@greenearthtrust.org",
    mobile: "9830000017",
    city: "Lucknow",
    district: "Lucknow",
    state: "UP",
    role: "member",
    user_type: "client",
    purposeCode: "PROBLEM",
    problemCategory: "Environmental Pollution PIL",
    verification_status: "Verified",
    purpose: "Legal Aid Requester: Urgent NGT Public Interest Litigation",
  },
  {
    id: "usr-cli-2",
    member_id: "26ICJ-REQ-0018",
    fullName: "Apex Technovations Pvt Ltd",
    name: "Apex Technovations Pvt Ltd",
    namePrefix: "M/s",
    email: "legal@apextech.com",
    mobile: "9830000018",
    city: "Bengaluru",
    district: "Bengaluru Urban",
    state: "Karnataka",
    role: "member",
    user_type: "client",
    purposeCode: "PROBLEM",
    problemCategory: "Corporate Contract Breach & IP Infringement",
    verification_status: "Verified",
    purpose: "Corporate Client: Commercial Arbitration Notice",
  },
  {
    id: "usr-cli-3",
    member_id: "26ICJ-REQ-0019",
    fullName: "Smt. Shanti Devi",
    name: "Smt. Shanti Devi",
    namePrefix: "Smt.",
    email: "shanti.devi@clients.icj.org",
    mobile: "9830000019",
    city: "Varanasi",
    district: "Varanasi",
    state: "UP",
    role: "member",
    user_type: "client",
    purposeCode: "PROBLEM",
    problemCategory: "Ancestral Property Dispute & Land Partition",
    verification_status: "Verified",
    purpose: "Legal Aid Applicant: Free Legal Aid Seeking Senior Citizen",
  },
  {
    id: "usr-cli-4",
    member_id: "26ICJ-REQ-0020",
    fullName: "Rohan Kulkarni",
    name: "Rohan Kulkarni",
    namePrefix: "Shri",
    email: "rohan.kulkarni@clients.icj.org",
    mobile: "9830000020",
    city: "Mumbai",
    district: "Mumbai Suburban",
    state: "Maharashtra",
    role: "member",
    user_type: "client",
    purposeCode: "PROBLEM",
    problemCategory: "Consumer Banking Fraud & Unfair Trade Practice",
    verification_status: "Verified",
    purpose: "Litigant Client: Consumer Forum Claim for Online Cyber Fraud",
  },
  {
    id: "usr-cli-5",
    member_id: "26ICJ-REQ-0021",
    fullName: "Global Logistics Workers Union",
    name: "Global Logistics Workers Union",
    namePrefix: "M/s",
    email: "union@globallogistics.org",
    mobile: "9830000021",
    city: "Kolkata",
    district: "Kolkata Port",
    state: "West Bengal",
    role: "member",
    user_type: "client",
    purposeCode: "PROBLEM",
    problemCategory: "Industrial Dispute & Unpaid Wage Recovery",
    verification_status: "Verified",
    purpose: "Union Client: Labour Court Collective Bargaining Claim",
  },

  // ─── TIER 2: 3 CERTIFIED NOTARY PUBLICS ───
  {
    id: "usr-notary-1",
    member_id: "26ICJ-NOT-0022",
    fullName: "Notary Public Ramesh Chand Goel",
    name: "Notary Public Ramesh Chand Goel",
    namePrefix: "Notary",
    email: "ramesh.notary@icj.org",
    mobile: "9840000022",
    city: "New Delhi",
    district: "Patiala House Courts",
    state: "Delhi",
    role: "member",
    user_type: "notary",
    serviceCategory: "Notary & Attestation",
    verification_status: "Verified",
    purpose: "Certified Govt Notary: Affidavit Verification & Document Seal",
  },
  {
    id: "usr-notary-2",
    member_id: "26ICJ-NOT-0023",
    fullName: "Notary Public Sunita Saxena",
    name: "Notary Public Sunita Saxena",
    namePrefix: "Notary",
    email: "sunita.notary@icj.org",
    mobile: "9840000023",
    city: "Lucknow",
    district: "High Court Lucknow Bench",
    state: "UP",
    role: "member",
    user_type: "notary",
    serviceCategory: "Notary & Attestation",
    verification_status: "Verified",
    purpose: "Certified Govt Notary: Power of Attorney & Agreement Verification",
  },
  {
    id: "usr-notary-3",
    member_id: "26ICJ-NOT-0024",
    fullName: "Notary Public Ashok Kadam",
    name: "Notary Public Ashok Kadam",
    namePrefix: "Notary",
    email: "ashok.notary@icj.org",
    mobile: "9840000024",
    city: "Mumbai",
    district: "Fort Bombay High Court",
    state: "Maharashtra",
    role: "member",
    user_type: "notary",
    serviceCategory: "Notary & Attestation",
    verification_status: "Verified",
    purpose: "Certified Govt Notary: Commercial Bond & Shipping Attestation",
  },

  // ─── TIER 2: 2 FRANCHISEE DIRECTORS ───
  {
    id: "usr-fran-1",
    member_id: "26ICJ-FRA-0025",
    fullName: "Kanpur Legal District Franchise Office",
    name: "Kanpur Legal District Franchise Office",
    namePrefix: "Dir.",
    email: "kanpur.franchise@icj.org",
    mobile: "9850000025",
    city: "Kanpur",
    district: "Kanpur District HQ",
    state: "UP",
    role: "member",
    user_type: "franchise",
    purposeCode: "FRANCHISE",
    franchiseCity: "Kanpur Nagar",
    verification_status: "Verified",
    purpose: "Authorized District Franchisee & Legal Aid Facilitation Hub",
  },
  {
    id: "usr-fran-2",
    member_id: "26ICJ-FRA-0026",
    fullName: "Pune District Legal Franchise Hub",
    name: "Pune District Legal Franchise Hub",
    namePrefix: "Dir.",
    email: "pune.franchise@icj.org",
    mobile: "9850000026",
    city: "Pune",
    district: "Pune District HQ",
    state: "Maharashtra",
    role: "member",
    user_type: "franchise",
    purposeCode: "FRANCHISE",
    franchiseCity: "Pune District",
    verification_status: "Verified",
    purpose: "Authorized District Franchisee & Bar Member Services Hub",
  },
];

/**
 * The 26 registry records above carry no login credentials. Without these the
 * password check can never pass, and every one of these accounts is unable to
 * sign in. Each record gets a username (the email local-part) and a hash of the
 * shared default password below.
 *
 * This is a demo/beta credential. Replace it with per-user passwords — and force
 * a change on first login — before this platform handles real member data.
 */
export const DEFAULT_SEED_PASSWORD = "IcjBeta@2026";

const withLoginCredentials = (member) => {
  const email = String(member.email || "");
  return {
    username: member.username || email.split("@")[0],
    passwordHash: member.passwordHash || hashPasswordSync(DEFAULT_SEED_PASSWORD),
    status: member.status || "Active",
    ready_for_login: true,
    ...member,
  };
};

const seedMembersWithCredentials = () => MASTER_26_SEED_MEMBERS.map(withLoginCredentials);

export const SeedEcosystemService = {
  /**
   * Master Command: Reset Database and Re-hydrate 26 Core Ecosystem Members in 1 millisecond.
   * Guarantees that no system reset ever clears the 26 Core Master Registry!
   */
  resetAndHydrate26CoreMembers() {
    const members = ENTERPRISE_SEED_USERS;
    if (typeof window === "undefined" || !window.localStorage) return members;

    window.localStorage.setItem("icj_members", JSON.stringify(members));
    window.localStorage.setItem("icj_enterprise_users", JSON.stringify(members));
    console.log("⚡ [SeedEcosystemService] 31 Core Ecosystem Members Re-Hydrated Cleanly!");
    return members;
  },

  /**
   * Get 31 Core Master Members
   */
  get26CoreMembers() {
    if (typeof window === "undefined" || !window.localStorage) return ENTERPRISE_SEED_USERS;
    try {
      const local = JSON.parse(window.localStorage.getItem("icj_members") || "[]");
      if (Array.isArray(local) && local.length >= ENTERPRISE_SEED_USERS.length) return local;
      return this.resetAndHydrate26CoreMembers();
    } catch {
      return this.resetAndHydrate26CoreMembers();
    }
  },
};

export default SeedEcosystemService;
